services:

  phpadmin:
    image: 'phpmyadmin/phpmyadmin:latest'
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      - PMA_USER=bn_opencart
    ports:
      - '${PHPADMIN_PORT}:80'

  mariadb:
    image: docker.io/bitnami/mariadb:11.2
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_opencart
      - MARIADB_DATABASE=bitnami_opencart
    ports:
      - '3306:3306'

  opencart:
    image: bitnami/opencart:4.0.2-3-debian-12-r33
    ports:
      - '${OPENCART_PORT}:8080'
      - '443:8443'
    environment:
      - OPENCART_HOST=${LOCAL_IP}:${OPENCART_PORT}
      - OPENCART_DATABASE_HOST=mariadb
      - OPENCART_DATABASE_PORT_NUMBER=3306
      - OPENCART_DATABASE_USER=bn_opencart
      - OPENCART_DATABASE_NAME=bitnami_opencart
      - ALLOW_EMPTY_PASSWORD=yes
    depends_on:
      - mariadb

  tests:
   image: testapp_tests:latest
   container_name: testapp_tests
   volumes:
     - ./allure-results:/app/allure-results:rw
   depends_on:
      - opencart
   command: ["/wait-for-it.sh", "opencart", "8080", "pytest", "--browser=chrome", "--browser_version=128.0", "--headless", "--selenoid", "--selenoid_url=http://selenoid:4444/wd/hub", "--url=http://${LOCAL_IP}:${OPENCART_PORT}/", "-s", "-v"]

networks:
  default:
    name: selenoid
    external: true